### ISSUE TITLE
Would it possible to use this alongside ember-cli ? 

### ISSUE THREAD

**Issue by richardaiko** [rwjblue/broccoli-derequire#2]
Hi there, Currently looking to derequire the app.js & vendor.js  (loader.js) files 

Here's what I have tried

var app = new EmberApp(defaults, {});
var tree = app.toTree();
var derequire = require('broccoli-derequire');
derequire(tree);

return tree;

**Comment by stefanpenner** [comment]
> var derequire = require('broccoli-derequire');

var tree = derequire(tree);

**Comment by richardaiko** [comment]
Thanks!, I knew I was doing something stupid. hah.   Worked fine for assets/vendor.js, But It doesn't seem to work for assets/appName.js though. am I missing something still?

**Comment by richardaiko** [comment]
I still see occurrences of `define('...')`  whereas when I look in vendor.js , Its replaced as expected to `enifed`

**Comment by richardaiko** [comment]
Ended up creating this : https://github.com/raikoroje/ember-derequire/blob/master/index.js .  Please let me know if there are cleaner alternatives :)  closing the issue
